// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe         = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var Page$HelloReactive = require("./page.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$HelloReactive.make("Hello!", /* array */[])), "index");

/*  Not a pure module */
